// <auto-generated />
using System;
using LunchNear.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LunchNear.API.Migrations
{
    [DbContext(typeof(LunchNearDbContext))]
    [Migration("20260730124137_TestRelations")]
    partial class TestRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LunchNear.Shared.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Classic flame-grilled burger",
                            Name = "Whopper",
                            Price = 8.99m,
                            Rating = 0m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Crispy chicken sandwich",
                            Name = "Chicken Sandwich",
                            Price = 7.99m,
                            Rating = 0m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Classic Italian pizza",
                            Name = "Margherita Pizza",
                            Price = 12.99m,
                            Rating = 0m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Four cheese pizza",
                            Name = "Quattro Formaggi",
                            Price = 14.99m,
                            Rating = 0m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Fresh salmon sushi roll",
                            Name = "Salmon Roll",
                            Price = 15.99m,
                            Rating = 0m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "Tempura shrimp and avocado",
                            Name = "Dragon Roll",
                            Price = 16.99m,
                            Rating = 0m,
                            RestaurantId = 3
                        });
                });

            modelBuilder.Entity("LunchNear.Shared.Models.DishRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DishId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Review")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.ToTable("DishRatings");
                });

            modelBuilder.Entity("LunchNear.Shared.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasLunchBuffet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasStudentDiscount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rating")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Avenyn, Gothenburg",
                            HasLunchBuffet = false,
                            HasStudentDiscount = true,
                            Name = "Burger King",
                            PriceRange = "Cheap",
                            Rating = 3.8m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Magasinsgatan, Gothenburg",
                            HasLunchBuffet = true,
                            HasStudentDiscount = true,
                            Name = "Pizzeria Marco",
                            PriceRange = "Medium",
                            Rating = 4.2m
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kungsgatan, Gothenburg",
                            HasLunchBuffet = true,
                            HasStudentDiscount = false,
                            Name = "Sushi Paradise",
                            PriceRange = "Expensive",
                            Rating = 4.5m
                        },
                        new
                        {
                            Id = 4,
                            Address = "Nils Ericson Plats, Gothenburg",
                            HasLunchBuffet = false,
                            HasStudentDiscount = true,
                            Name = "Tacos El Amigo",
                            PriceRange = "Cheap",
                            Rating = 4.1m
                        },
                        new
                        {
                            Id = 5,
                            Address = "Jarntorget, Gothenburg",
                            HasLunchBuffet = true,
                            HasStudentDiscount = true,
                            Name = "Thai Kitchen",
                            PriceRange = "Medium",
                            Rating = 4.3m
                        },
                        new
                        {
                            Id = 6,
                            Address = "Storgatan, Gothenburg",
                            HasLunchBuffet = false,
                            HasStudentDiscount = false,
                            Name = "Steakhouse Premium",
                            PriceRange = "Expensive",
                            Rating = 4.7m
                        },
                        new
                        {
                            Id = 7,
                            Address = "Heden, Gothenburg",
                            HasLunchBuffet = false,
                            HasStudentDiscount = true,
                            Name = "Kebab House",
                            PriceRange = "Cheap",
                            Rating = 3.9m
                        },
                        new
                        {
                            Id = 8,
                            Address = "Vasaplatsen, Gothenburg",
                            HasLunchBuffet = true,
                            HasStudentDiscount = false,
                            Name = "Pasta Perfetto",
                            PriceRange = "Medium",
                            Rating = 4.4m
                        });
                });

            modelBuilder.Entity("LunchNear.Shared.Models.StudentDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("StudentDiscounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "20% off with valid student ID",
                            DiscountPercentage = 20,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Buy one pizza get second 50% off",
                            DiscountPercentage = 50,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "15% student discount with ID",
                            DiscountPercentage = 15,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 4,
                            Description = "10% off for students every day",
                            DiscountPercentage = 10,
                            RestaurantId = 5
                        },
                        new
                        {
                            Id = 5,
                            Description = "Free drink with student discount",
                            DiscountPercentage = 5,
                            RestaurantId = 7
                        });
                });

            modelBuilder.Entity("LunchNear.Shared.Models.Dish", b =>
                {
                    b.HasOne("LunchNear.Shared.Models.Restaurant", "Restaurant")
                        .WithMany("Dishes")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("LunchNear.Shared.Models.DishRating", b =>
                {
                    b.HasOne("LunchNear.Shared.Models.Dish", "Dish")
                        .WithMany("Ratings")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("LunchNear.Shared.Models.StudentDiscount", b =>
                {
                    b.HasOne("LunchNear.Shared.Models.Restaurant", "Restaurant")
                        .WithMany("StudentDiscounts")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("LunchNear.Shared.Models.Dish", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("LunchNear.Shared.Models.Restaurant", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("StudentDiscounts");
                });
#pragma warning restore 612, 618
        }
    }
}
